spring.application.name=vedanta-computer-api
server.port=9191
# ==============================================================
# Database Configuration Profile (PostgreSQL)
# ==============================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/vedanta_db
spring.datasource.username=postgres
spring.datasource.password=Sukantg#007
spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================================================
# JPA / Hibernate Configuration Settings
# ==============================================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==============================================================
# Security / JWT Infrastructure Configurations
# ==============================================================
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration-ms=86400000

